sycl_EXTERNAL_DEPENDS := TBB EIGEN SYCL
SYCLCore_DEPENDS := Framework
Test1_DEPENDS := Framework SYCLCore DataFormats
Test2_DEPENDS := Framework SYCLCore
BeamSpotProducer_DEPENDS := Framework SYCLCore DataFormats
PixelTriplets_DEPENDS := Framework SYCLCore SYCLDataFormats
PixelTrackFitting_DEPENDS := Framework SYCLCore SYCLDataFormats
SiPixelRawToDigi_DEPENDS := Framework SYCLCore SYCLDataFormats CondFormats DataFormats
